[package]
name = "orchestrator"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
vessels = { path = "../../", features = ["core"] }
test_vessel = { path = "../test_vessel" }
futures = "0.3.1"
serde = { version = "1.0.101", features = ["derive"] }
