[package]
name = "derive"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
syn = { features = ["full"], version = "1.0.7" }
quote = "1.0.2"
synstructure = "0.12.1"
proc-macro-error = "0.3.4"
