[package]
name = "test-vessel"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = { version = "0.3.5", default-features = false }
core-futures-io = { git = "https://github.com/noocene/core-futures-io" }
